#!/usr/bin/env bash
set -eEu
set -o pipefail

. sdlc/functions.sh

indent() {
    echo "       $*"
}

echo
echo "[INFO] update table-of-contents"
md_toc --in-place --skip-lines 1 commonmarker --header-levels 6 README.md

cd src/
export BUNDLE_GEMFILE=Gemfile

# https://stackoverflow.com/a/42439671
rm -fr pkg

bundle exec octool _doc
bundle exec rake package

echo
echo "[INFO] Build docker image"
export OCTOOL_VERSION="${VERSION}"
docker-compose build
