#!/bin/bash
set -eu
set -o pipefail

. sdlc/functions.sh

DOCKER_HUB_USER="${DOCKER_HUB_USER:-unset}"
DOCKER_HUB_TOKEN="${DOCKER_HUB_TOKEN:-unset}"
if [[ "${DOCKER_HUB_USER}" = unset ]] || [[ "${DOCKER_HUB_TOKEN}" = unset ]]; then
    echo "[FAIL] DOCKER_HUB_USER or DOCKER_HUB_TOKEN is unset"
    exit 1
fi

docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_TOKEN}"
# Push optimistic tag.
docker-compose push texlive
docker logout

echo
echo "[INFO] Trigger update on MicroBadger"
run curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/octool/pX_Ha2ULC4a-i6SYyAtPYiTUX5I='
echo

output="$(gem search --remote -a octool)"
if echo "${output}" | grep -q "${VERSION}"; then
    # Be informative, but don't fail.
    # This enables to merge changes to non-gem files, such as README.
    echo "[WARN] octool ${VERSION} has already been published."
    exit
fi

if [[ "${GEM_HOST_API_KEY:-unset}" == unset ]]; then
    echo "[FAIL] GEM_HOST_API_KEY is unset"
    exit 1
fi

gem --version
gem push "src/pkg/octool-${VERSION}.gem"
