#!/usr/bin/env bash
set -eEu
set -o pipefail

. sdlc/functions.sh

echo "[INFO] Validate schemas"
BUNDLE_GEMFILE=src/Gemfile bundle exec octool validate schemas

echo
echo "[INFO] Validate data for example system"
docker-compose run validate

echo
echo "[INFO] Export data to CSV for example system"
docker-compose run csv

echo
echo "[INFO] Build SSP for example system"
SSP_CID="ssp_container"
docker rm -fv "${SSP_CID}" &>/dev/null || :
docker-compose run --name "${SSP_CID}" ssp
for doc_type in md pdf docx; do
    docker cp "${SSP_CID}:/tmp/ssp.${doc_type}" /tmp/
    echo "[INFO] copied ${doc_type} to /tmp/ssp.${doc_type}"
done

echo
echo "[INFO] Run declarative checks"
pre-commit run --all-files --hook-stage manual

# Show positive feedback to developer.
echo
echo "[PASS] Tests OK"
