---

Layout/IndentationWidth:
    Description: Use 4 spaces for indentation.
    # Number of spaces for each indentation level.
    Width: 4
    IgnoredPatterns: []

Lint/UnusedBlockArgument:
    Description: Checks for unused block arguments.
    AllowUnusedKeywordArguments: false
    Exclude:
        - src/bin/octool

Metrics/LineLength:
    Description: Limit lines to 100 characters.
    Max: 100

Style/EmptyMethod:
    Description: Checks the formatting of empty method definitions.
    EnforcedStyle: expanded

Style/Semicolon:
    Description: Don't use semicolons to terminate expressions.
    AllowAsExpressionSeparator: true

Style/SymbolArray:
    Description: Use %i or %I for arrays of symbols.
    EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
    Description: Checks for trailing comma in array literals.
    EnforcedStyleForMultiline: comma

Style/WordArray:
    Description: Brackets are more intuitive to read because they do not use magic syntax.
    EnforcedStyle: brackets
