---
type: map
class: Config
mapping:
    schema_version:
        desc: |
            Must match one of the schema directories in the octool source.
        required: true
        type: str

    logo:
        desc: Image for title page.
        required: false
        type: map
        class: Logo
        mapping:
            path:
                desc: Path to image.
                type: str
                required: true
            width:
                desc: Width of image, such as "1in" or "254mm"
                type: str
                required: true

    name:
        desc: Human-friendly to appear in the SSP.
        required: true
        type: str

    overview:
        desc: Human-friendly description to appear in the SSP.
        required: true
        type: str

    maintainers:
        desc: Who should somebody contact for questions about this SSP?
        required: true
        type: seq
        sequence:
            - type: str

    metadata:
        desc: Optional metadata.
        required: false
        type: map
        class: Metadata
        mapping:
            abstract:
                desc: Abstract appears in document metadata.
                required: false
                type: str
            description:
                desc: Description appears in document metadata.
                required: false
                type: str
            '=':
                desc: Arbitrary key:value pair of strings.
                type: str

    includes:
        desc: Additional files to include from the system repo.
        required: true
        type: seq
        sequence:
            - type: map
              class: Include
              mapping:
                  type:
                      required: true
                      type: str
                      enum:
                          - certification
                          - component
                          - standard
                  path:
                      desc: Path must be relative within the repo.
                      required: true
                      type: str
