# frozen_string_literal: true

source 'https://rubygems.org'
gemspec

#
# https://renovate.whitesourcesoftware.com/
# currently supports dependencies in Gemfile but not gemspec.
#

gem 'daru', '0.2.2'
gem 'etc', '1.1.0'
gem 'gli', '2.19.0'
gem 'kwalify', '0.7.2'
gem 'pandoc-ruby', '2.1.4'
gem 'paru', '0.4.0.1'

group :development do
    gem 'rake', '>= 13.0', '< 13.1'
    gem 'rdoc', '>= 6.2', '< 6.3'
end
